import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'
import { StarknetProvider } from '@/components/starknet-provider'
import './globals.css'
import AppLayout from '@/components/app-layout'

const outfit = Outfit({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={outfit.className}>
        <StarknetProvider>
          <AppLayout>{children}</AppLayout>
        </StarknetProvider>
      </body>
    </html>
  );
}